Capstone project module1
leloufadel/capstone-1 pull request #2
Opened 2023-04-27 10:43 UTC by leloufadel

In this PR: 
I build the home page and about page.
Each of these pages has a mobile and desktop version
The home page has a link in the menu to the About page.
create Navbar Menu for the desktop version
create a hamburger menu for the mobile version
The section "Featured speakers" was created dynamically in JavaScript.
Used a JavaScript variable with the data about the speakers and used it when the page loads to create the HTML for this section dynamically.

2023-04-27 11:55 UTC, Ibizugbe requested changes
Hi @leloufadel 👋👋, 

![tryagain](https://user-images.githubusercontent.com/64643995/234846661-dfea58ae-6b33-4090-b5e1-03145effb41a.gif)


Good job so far!👍
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights✅✅✅

- [x] Linters are properly setup and they are passing👍.
- [x] Github flow have been used👍.
- [x]  Speaker section have been rendered dynamically using the content from the array of objects created👍.


## Required Changes ♻️

- [ ] Nice job on your video presentation👍. lrt's make sure we stick to the required instructions when recording your project👍. Kindly walk us through your project on your laptop screen while presenting and stick to the given instructions for presenting the video👍. Kindly take a look at the image below and try to follow the instructions in your next recording👍.
<img width="830" alt="video" src="https://user-images.githubusercontent.com/64643995/234847352-d236df0a-ce17-4150-9a22-6a76c82fa915.png">

- [ ] The live demo on your readme file doesn't lead to this project😉 I think you might have mistakenly placed the link to your portfolio there, kindly make the necessary change as the live demo should contain the link to your project👍.


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-27 11:55 UTC, Ibizugbe commented on about.html
> +          </p> -->
Kindly take away every comment block of code in your project as they make your codebase messy and give it a less professional look👍,

2023-04-27 11:55 UTC, Ibizugbe commented on index.html
> +      <h3>Main Program</h3>
I suggest this should be a `h2` instead. this obeys the header hierarchy rule as this is the first header in this section it should use the hierarchy next to the main `h1` header👍 This makes your page more semantic👍 Kindly make the necessary change and ensure subsequent headers in your project follow the hierarchy😉 by this, other headers in this section will make use of `h3`

2023-04-27 11:55 UTC, Ibizugbe commented on about.html
> +    </footer>
Just as shown in the design, your About footer should have a dark background, making it a bit different from the home footer👍😉

design
<img width="570" alt="image" src="https://user-images.githubusercontent.com/64643995/234850621-8e9f83cc-54d7-4cc2-a7cb-5c763975d2b5.png">

yours
<img width="946" alt="image" src="https://user-images.githubusercontent.com/64643995/234850781-27491717-0b2f-406b-bf76-f624ca9e696a.png">

Kindly make your about footer to match the design as this is a requirement in this milestone👍.

2023-04-27 11:55 UTC, Ibizugbe commented on about.html
> +    </section>
Your event cards section looks a bit different from the design, kindly take note of the sizes of the image and the spacings and make the necessary changes👍.

yours
<img width="938" alt="image" src="https://user-images.githubusercontent.com/64643995/234851316-749aa177-064a-4818-b209-64e7eb616645.png">

design
<img width="548" alt="image" src="https://user-images.githubusercontent.com/64643995/234851447-5c89e2a7-8bc6-4dc5-b959-6a89a4a949d6.png">

same on mobile, kindly ensure they are stacked and the right font properties are used👍.
yours
<img width="274" alt="image" src="https://user-images.githubusercontent.com/64643995/234851736-1eeebfa5-d9a9-4ba0-b6a6-71d9da300962.png">

design
<img width="291" alt="image" src="https://user-images.githubusercontent.com/64643995/234851847-f4ac7658-e711-423b-83c8-6fd9f3207f31.png">


In general, Kindly ensure your entire mobile section is responsive and it sticks to the the design. take note of the font properties, colors and the position of each elements both on mobile and on web👍.

<img width="278" alt="image" src="https://user-images.githubusercontent.com/64643995/234852430-837ebac7-1de4-435d-9245-68278819c7ba.png">

2023-04-27 11:55 UTC, Ibizugbe commented on main.js
> +
Kindly style your speaker section to match the given design😉 Take note of the position of the elements, the colors used for each element and their font properties, and the spacings👍👍 and kindly ensure it is responsive( it applies both on mobile screen)👍  Don't forget we are required to stick to the given design in this milestone and make our project responsive👍.

yours
<img width="925" alt="image" src="https://user-images.githubusercontent.com/64643995/234852915-7016cd23-6602-46fe-ab82-9066a62686f7.png">

design
<img width="664" alt="image" src="https://user-images.githubusercontent.com/64643995/234853009-5d0c045b-f367-42d4-97f7-f4f8dbd2186f.png">

2023-04-27 11:55 UTC, Ibizugbe commented on about.html
> +      <img class="logo" src="Assets/semless.gif"alt="logo">
For semantic reasons, I suggest you ensure the brand logo is wrapped in `a` tag that links to the homepage as this improves the Users experience by making the homepage accessible at any point👍.

2023-04-27 11:55 UTC, Ibizugbe commented on index.html
> +  </footer>
On the mobile screen, the index page doesn't have a footer😉 It rather ends with a button to see more speakers. kindly make the necessary changes and ensure you stick to the design on the mobile screen👍.

yours
<img width="283" alt="image" src="https://user-images.githubusercontent.com/64643995/234854183-88d05c86-b71b-467b-8960-ed65f47bdc84.png">

design
<img width="293" alt="image" src="https://user-images.githubusercontent.com/64643995/234854302-38e0652f-797b-45d5-8676-4c0fa7597a52.png">

2023-04-28 03:39 UTC, Reem-lab requested changes
# Hi @leloufadel, 👋🏻👋🏻

Great work on making the changes requested by a previous reviewer 👏 🔥✅🎉🎉
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media1.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>



 ## Highlights

- No Linters error ✅
- Followed GitHub Flow 🤩
- Great working on the functionality for using JS for create the speakers section 🔥
- Good job working on the design 🚀💯
- Professional README ⭐
- Great working on the presentation video 🔥
- Deployed well 🎉🎉

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-04-28 03:39 UTC, Reem-lab commented on about.html
> +          </p> -->
- [ ] Great job working on some of the requirements but I think it would be great if you removed the commented code form your project as requested by the previous code reviewer since it is very important to make your code clean base 🎉🔥🚀

2023-04-28 03:39 UTC, Reem-lab commented on about.html
> +      </ul>
- [ ] As requested by the prvious code reviewer  I think it would be great if you make the width and height for the images here smaller since I can see in your design you have bigger width and height so please minimize the width and height for it a little bit to match the given design as much as possible 🚀🔥✨

- Your
![image](https://user-images.githubusercontent.com/58553711/235046725-3f3f180b-b2ef-4b0d-915b-ccac870b75c0.png)



- Given
![image](https://user-images.githubusercontent.com/58553711/235010357-c4603c33-8ef7-47c5-b4f6-d48c3b553752.png)

2023-04-28 03:39 UTC, Reem-lab commented on index.html
> +  </footer>
- [ ] As requested by the previous code reviewer asked here I think it would be Great if you remove  the footer and partner  but in the Mobile version in Home page if you check the given design there is no partner section and footer so I recommend to remove them from the home page in the mobile version 💯🔥🚀✨

- Your design
![image](https://user-images.githubusercontent.com/58553711/235047458-336d50da-82ec-4449-adb2-5abdef82791d.png)


- Given
![image](https://user-images.githubusercontent.com/58553711/235008775-77c59901-95d4-4e8c-b4c3-c59b7c9bd200.png)

2023-04-28 03:39 UTC, Reem-lab commented on index.html
> +        <div class="program-item">
- [ OPTIONAL ] I think it would be great if you make you main program section divs aligned like the given template since your design is different than the given design if you see the in Home page for mobile version the icon and the heading and the text aligned as flex beside each other but you  in you case under each other kindly change them to match the given design 🚀🔥🎉✅ and I am assiging as optional because the previous rebiewer didn't mention it but it still very important to update it ✅

- Yours
![image](https://user-images.githubusercontent.com/58553711/235048163-7770da40-e48b-43b9-a9d5-3afbf64331e1.png)

- given
![image](https://user-images.githubusercontent.com/58553711/235048194-06aad957-f87d-40ca-879c-bab09e8b2ae7.png)

2023-04-28 03:39 UTC, Reem-lab commented on README.md
> +# 📖 Capstone Project <a name="about-project"></a>
- [ OPTIONAL ] I suggest to add in your acknowledgment section to give appropriate credit to the author. Therefore, you must do it in the README of your project. since it is one of the requirements ✅🔥🚀 and I am assiging as optional because the previous rebiewer didn't mention it but it still very important to update it ✅

2023-04-28 14:13 UTC, sumairq approved these changes
### Hi @leloufadel , 

<img src="https://media3.giphy.com/media/BPJmthQ3YRwD6QqcVD/giphy.gif"/>

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

## Highlights
✔️ Good commit history
✔️Linters are passing
✔️Very professional README
✔️Correct Github flow
✔️Descriptive PR


Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-04-28 14:17 UTC, merged